name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.9.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UBUNTU_IP }}
        username: ${{ secrets.UBUNTU_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        node-version: ${{ matrix.node-version }}
        script: |
            mkdir erp_frontend 
            cd erp_frontend 
            git clone git@github.com:vedanshu-insonix/erp-react-frontend.git 
	    
